apiVersion: apps/v1
kind: Deployment
metadata:
  name: printdotnet6
  labels:
    app: printdotnet6
spec:
  replicas: 5
  selector:
    matchLabels:
      app: printdotnet6
  template:
    metadata:
      labels:
        app: printdotnet6
    spec:
      containers:
      - name: printdotnet6
        image: mastrauckas/printdotnet6:v1.0
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule