apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-web-app
  labels:
    webapp: nginx
spec:
  replicas: 4
  selector:
    matchLabels:
      webapp: nginx
  template:
    metadata:
      labels:
        webapp: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
      topologySpreadConstraints:
         - maxSkew: 1
           minDomains: 1
           topologyKey: zone
           whenUnsatisfiable: DoNotSchedule
           labelSelector:
            matchLabels:
              webapp: nginx
         - maxSkew: 1
           minDomains: 1
           topologyKey: region
           whenUnsatisfiable: DoNotSchedule
           labelSelector:
            matchLabels:
              webapp: nginx 