apiVersion: apps/v1
kind: Deployment
metadata:
  name: printdotnet8
  labels:
    app: printdotnet8
spec:
  replicas: 10
  selector:
    matchLabels:
      app: printdotnet8
  template:
    metadata:
      labels:
        app: printdotnet8